package cachedcarthage

import "github.com/stretchr/testify/mock"

// MockProjectStateProvider is an autogenerated mock type for the ProjectStateProvider type
type MockProjectStateProvider struct {
	mock.Mock
}

// ParseState provides a mock function with given fields: project
func (m *MockProjectStateProvider) ParseState(project Project) (ProjectState, error) {
	args := m.Called(project)
	return args.Get(0).(ProjectState), args.Error(1)
}

func (m *MockProjectStateProvider) GivenParseStateFails(reason error) *MockProjectStateProvider {
	m.On("ParseState", mock.Anything).Return(ProjectState{}, reason)
	return m
}

func (m *MockProjectStateProvider) GivenParseStateSucceeds(projectState ProjectState) *MockProjectStateProvider {
	m.On("ParseState", mock.Anything).Return(projectState, nil)
	return m
}
