package cachedcarthage

import mock "github.com/stretchr/testify/mock"

// MockProjectStateProvider is an autogenerated mock type for the ProjectStateProvider type
type MockProjectStateProvider struct {
	mock.Mock
}

// ParseState provides a mock function with given fields: project
func (m *MockProjectStateProvider) ParseState(project Project) (ProjectState, error) {
	ret := m.Called(project)

	var r0 ProjectState
	if rf, ok := ret.Get(0).(func(Project) ProjectState); ok {
		r0 = rf(project)
	} else {
		r0 = ret.Get(0).(ProjectState)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Project) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (m *MockProjectStateProvider) GivenParseStateFails(reason error) *MockProjectStateProvider {
	m.On("ParseState", mock.Anything).Return(ProjectState{}, reason)
	return m
}

func (m *MockProjectStateProvider) GivenParseStateSucceeds(projectState ProjectState) *MockProjectStateProvider {
	m.On("ParseState", mock.Anything).Return(projectState, nil)
	return m
}
