package cachedcarthage

import mock "github.com/stretchr/testify/mock"

// MockCarthageCache is an autogenerated mock type for the CarthageCache type
type MockCarthageCache struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (m *MockCarthageCache) Commit() error {
	args := m.Called()
	return args.Error(0)
}

// CreateIndicator provides a mock function with given fields:
func (m *MockCarthageCache) CreateIndicator() error {
	args := m.Called()
	return args.Error(0)
}

// IsAvailable provides a mock function with given fields:
func (m *MockCarthageCache) IsAvailable() (bool, error) {
	args := m.Called()
	return args.Bool(0), args.Error(1)
}

func (m *MockCarthageCache) GivenIsAvailableFails(reason error) *MockCarthageCache {
	m.On("IsAvailable").Return(false, reason)
	return m
}

func (m *MockCarthageCache) GivenIsAvailableSucceeds(result bool) *MockCarthageCache {
	m.On("IsAvailable").Return(result, nil)
	return m
}

func (m *MockCarthageCache) GivenCommitFails(reason error) *MockCarthageCache {
	m.On("Commit").Return(reason)
	return m
}

func (m *MockCarthageCache) GivenCommitSucceeds() *MockCarthageCache {
	m.On("Commit").Return(nil)
	return m
}

func (m *MockCarthageCache) GivenCreateIndicatorFails(reason error) *MockCarthageCache {
	m.On("CreateIndicator").Return(reason)
	return m
}

func (m *MockCarthageCache) GivenCreateIndicatorSucceeds() *MockCarthageCache {
	m.On("CreateIndicator").Return(nil)
	return m
}
