package cachedcarthage

import mock "github.com/stretchr/testify/mock"

// MockFileCache is an autogenerated mock type for the FileCache type
type MockFileCache struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (m *MockFileCache) Commit() error {
	ret := m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncludePath provides a mock function with given fields: _a0
func (m *MockFileCache) IncludePath(_a0 string) {
	m.Called(_a0)
}

func (m *MockFileCache) GivenIncludeSucceeds() *MockFileCache {
	m.On("IncludePath", mock.Anything).Return()
	return m
}

func (m *MockFileCache) GivenCommitFails(reason error) *MockFileCache {
	m.On("Commit").Return(reason)
	return m
}

func (m *MockFileCache) GivenCommitSucceeds() *MockFileCache {
	m.On("Commit").Return(nil)
	return m
}
