package main

import mock "github.com/stretchr/testify/mock"

// MockFileProvider is an autogenerated mock type for the FileProvider type
type MockFileProvider struct {
	mock.Mock
}

// LocalPath provides a mock function with given fields: path
func (m *MockFileProvider) LocalPath(path string) (string, error) {
	args := m.Called(path)
	return args.String(0), args.Error(1)
}

func (m *MockFileProvider) GivenLocalPathSucceeds(path string) *MockFileProvider {
	m.On("LocalPath", mock.Anything).Return(path, nil)
	return m
}

func (m *MockFileProvider) GivenLocalPathFails(reason error) *MockFileProvider {
	m.On("LocalPath", mock.Anything).Return("", reason)
	return m
}
